### PR TITLE
Some love for out mascot

### PR DESCRIPTION
**Pull request by rikard-softgear**
Added a small semi-transparent _MiSTer-kun_ to the lower right corner. :3

### CODE REVIEW

**Comment by rikard-softgear** [comment]
20200221_213048-800x600

**Comment by sorgelig** [comment]
Too many logos from my point of view.

**Comment by sacredbanana** [comment]
Not enough logos. Can you add an extra logo that bounces across the screen similar to the old DVD video logo?

**Comment by rikard-softgear** [comment]
I'm fine with this. Just a question, is an external "watermark.png" just as bad of an idea? :)

**Comment by sorgelig** [comment]
It's like "Hey Toyota, make your logo removable, may be i would like to put a Nissan logo" ;)

**Comment by rikard-softgear** [comment]
OK, I'm closing this one. ;)

**Pull request closed without merging**
