### PR TITLE
Miniz update

### PR DESCRIPTION
**Pull request by zakk4223**
Update miniz to latest (2.1.0) release.
Rever libchdr to use inflateReset

### CODE REVIEW

**Comment by zakk4223** [comment]
I also switched my build environment to use the linaro release on the wiki instead of the docker image so there shouldn't be any surprise external dependencies this time

**Comment by sorgelig** [comment]
Where is inflateReset() defined? libz? So you want to tell you pass foreigner structure to libz while using miniz? This is definitely wrong

**Comment by zakk4223** [comment]
It's part of miniz. Please see miniz.h

**Comment by sorgelig** [comment]
oh, i see. they added this function

**Pull request merged**
