### PR TITLE
Custom fonts loaded from /root/config/Font.dat

### PR DESCRIPTION
**Pull request by rikard-softgear**
I also included a folder with 97 fonts to choose from (and preview images of them). Just rename a .dat font file to Font.dat and put it into your config folder.

### CODE REVIEW

**Comment by sorgelig** [comment]
I will make it a little differently. But i will use your big collection of font.
i've sent you an invitation for MiSTer-devel group. After accepting you will be able to create a repository these. I want to ask you to make a font repository as i want to keep it separate from Main repo.

**Comment by sorgelig** [comment]
Btw, for simplified parsing please remove spaces from file names. Use _ instead.

**Comment by sorgelig** [comment]
One more update: font can have smaller size without pseudo-graphics. Since it's overwiting the existing font, the remaining part will be preserved. So, may be it would be better to strip the pseudo-graphics at the end and use original one.

**Comment by rikard-softgear** [comment]
Thanks, I will reduce the charset to char 32-128, thus reducing the size to 96×8=768 bytes.

**Comment by sorgelig** [comment]
It's better not to cut the front chars. It will change the loading address, so it won't be so flexible.

**Comment by sorgelig** [comment]
After thinking, it's ok to cut the front symbols. I will detect the type by size.
I also think about supporting non-transformed fonts, so it will be easier to add new fonts. MiSTer will rotate the chars upon loading. So, please transform your fonts back to normal orientation.

**Comment by sorgelig** [comment]
New version on repo. It uses standard fonts. Check the MiSTer.ini for new option.

**Comment by rikard-softgear** [comment]
Should loading adress be stored in the font, maybe the last byte?

________________________________
Från: sorgelig <notifications@github.com>
Skickat: den 23 mars 2019 08:33:23
Till: MiSTer-devel/Main_MiSTer
Kopia: Rikard Bengtsson; Author
Ämne: Re: [MiSTer-devel/Main_MiSTer] Custom fonts loaded from /root/config/Font.dat (#70)


After thinking, it's ok to cut the front symbols. I will detect the type by size.
I also think about supporting non-transformed fonts, so it will be easier to add new fonts. MiSTer will rotate the chars upon loading. So, please transform your fonts back to normal orientation.

**Comment by rikard-softgear** [comment]
I've made a repo with all the .pf files + previews now. Most of them 768 bytes. Phew! 😊

________________________________
Från: sorgelig <notifications@github.com>
Skickat: den 23 mars 2019 09:58:10
Till: MiSTer-devel/Main_MiSTer
Kopia: Rikard Bengtsson; Author
Ämne: Re: [MiSTer-devel/Main_MiSTer] Custom fonts loaded from /root/config/Font.dat (#70)


New version on repo. It uses standard fonts. Check the MiSTer.ini for new option.

**Comment by sorgelig** [comment]
Good!

**Pull request closed without merging**
