### PR TITLE
fix for issue #258

### PR DESCRIPTION
**Pull request by c0d3h4x0r**
use vid+pid for matching unique physical device across disconnect/reconnect

### CODE REVIEW

**Comment by sorgelig** [comment]
This is not correct way. It will break the logic. If you have several gamepads of the same model, then they will have the same vid+pid. The only possible way to avoid that issue is don't let your gamepad to go to sleep, i.e. if you play the game, then play. Once gamepad mapped to player is disconnected, it's un-mapped. Actually it's not fatal. The case you described in issue is about playing alone. So, once you return back to game, use the same gamepad (don't touch keyboard or other sleeping devices) and it will be automatically assigned to the same (first) player.

**Comment by sorgelig** [comment]
i close this PR as the method of restoring the map is unacceptable. It completely breaks the case when you have several gamepads with the same vid/pid and all then will be mapped to the same player.

**Comment by c0d3h4x0r** [comment]
The scenario (one person playing alone, using a Bluetooth keyboard and one Blueyooth gamepad) is badly broken.  This is a real problem that needs to be fixed.  Other people in the Classic Gaming Discord have been complaining about it too.  Please do not close those; instead, let’s work together to figure out a way to fix it.  This issue makes MiSTer basically unusable for many people.

**Comment by sorgelig** [comment]
There is a discussion in your issue. So i've posted there.

**Pull request closed without merging**
