### PR TITLE
Main loop latency reduction with coroutines

### PR DESCRIPTION
**Pull request by dholm**
Schedules tasks in the main loop using coroutines so that long running
tasks, particularly relating to the UI, can yield execution in order to
call the poll functions at a tighter interval.

Yields at an interval during the loading of directory entries as well as
while sorting them in order to avoid starving the poll functions while
entering directories containing a large number of files.

The maximum time between calls to `user_io_poll` in the main loop were
measured while loading a folder containing 29026 entries:

 - Original main-loop:       591ms
 - With coroutines + yields:  29ms

The amount of time it takes to load and sort the 29k entries:

 - Original main-loop:       591ms
 - With coroutines + yields: 686ms

By increasing the value of `YieldIterations` in `file_io.cpp` the load
time will decrease while increasing the delay between calls to
`user_io_poll`.

### CODE REVIEW

**Comment by sorgelig** [comment]
Looks interesting. Never heard about co-routines before.

**Comment by dholm** [comment]
It's starting to grow in popularity now because it is very effective if you are developing services that need to serve large number of requests with low overhead.  It is one of the fundamental features of Go (the Google programming language) where it is called goroutines.

I'm considering taking a look at the input handling next.  The system calls are the main contributors to the latency and one way to improve this would be to run the `poll` from `input_test` in a separate thread pinned to core 0 and then push events through a lock-free queue to the input code running in the main loop.  I'll try to put something simple together for you to review, unless you think it's unnecessary?

**Comment by sorgelig** [comment]
it seems you didn't pull my changes before you made PR - so all my fixes against warnings were reverted..

**Comment by dholm** [comment]
Are you sure?  I rebased just before I pushed this change to GitHub.

**Comment by sorgelig** [comment]
False alarm. The warnings were from other file i didn't tweak yet. Strange there was no warnings before. Anyway, it's fixed now.

**Comment by sorgelig** [comment]
is this code:
```
	co_delete(co_ui);
	co_delete(co_poll);
	co_delete(co_scheduler);
```
really executed? It looks like dead code.

**Comment by sorgelig** [comment]
btw, it seems you are the first one who didn't start with "let's add sleep(x) in the main thread to reduce CPU usage" ;)

**Comment by dholm** [comment]
> is this code:
> 
> ```
> 	co_delete(co_ui);
> 	co_delete(co_poll);
> 	co_delete(co_scheduler);
> ```
> really executed? It looks like dead code.

It's dead but I always add cleanup code in the proper places.  If someone wants to change the application in the future so that it can do a clean shutdown they don't have to worry about where the cleanup code is supposed to be.

**Comment by dholm** [comment]
> btw, it seems you are the first one who didn't start with "let's add sleep(x) in the main thread to reduce CPU usage" ;)

There are so many better things you can do with CPU cycles other than wasting them on sleeping. :)

**Comment by sorgelig** [comment]
Especially when CPU has no PM and cannot sleep :)

**Comment by sorgelig** [comment]
so coroutines is lightweight threading with one important feature - you can control at which places thread can be switched to another one.
Too bad it also requires splitting the stack so need to be careful not to overflow it.

**Comment by dholm** [comment]
Sure, I will take a stab at it after I'm done with the latency reduction stuff in `input_poll`.

**Pull request merged**
