### PR TITLE
Added controller handling for new N64 options

### PR DESCRIPTION
**Pull request by trbocode**
Some games use two controllers, or hold analog stick in the right hand

### CODE REVIEW

**Comment by sorgelig** [comment]
please move it into n64 support code.

**Comment by trbocode** [comment]
I tried to cache the controller variables, but didn't find a contained way to do it. What would be the best way?

**Comment by sorgelig** [comment]
I think you need to talk to @RobertPeip to coordinate it between HPS and core.

**Comment by trbocode** [comment]
I think this should be good enough - No 3 calls to sscanf anymore

**Pull request merged**
