### PR TITLE
add support for JammaSD input device

### PR DESCRIPTION
**Pull request by vikbez**
JammaSD is a device that is commonly used in arcade machines to convert input buttons to keyboard keys (for using a computer inside a cabinet)

I coded something that works so far: emulating 2 joysticks depending on what input the mister receive from the JammaSD;

I don't know if it's the right way to do it and the right place to put the test, but it works so far.

There are more devices working like that (Jpac for example); I took a long time to think how this should be implemented and made this, but I could be wrong.

### CODE REVIEW

**Comment by sorgelig** [comment]
with such patch you won't be able to define keys per core

**Comment by vikbez** [comment]
What about something like that then ?

**Comment by sorgelig** [comment]
I plan to publish info how i've adapted the arcade cabinet's inputs for MiSTer using Arduino Micro.
Basically you don't need any extra components. Just buttons (and spinner) connected to arduino board. And it works fine without any changes in code.
Then may be you can see if you want to go that route. 
Modern arcade cabinets input board are full of weird things.

**Comment by vikbez** [comment]
Well I'm not doing this for me (I used a teensy in my cabinet).
I  wanted to help people around me that all have a jammasd and want to play with a mister to have a "easy" way of doing it.
Does a PR with this will be accepted if it seems correct to you or do you not prefer having this in the main_mister code ?
Maybe you have a better idea for the implementation ?

**Comment by mcarquigny** [comment]
For members of the communities I belong to JammaSD is almost the default configuration in most cabinets.
I don't know if the solution proposed by vik "as it is" is sufficient or if it needs more work, but having this compatibility would be a real plus (at least for me and I guess for a lot of people) !

**Comment by sorgelig** [comment]
It's unclear if all jammasd controls use the same vid/pid, otherwise there is no way to distinguish it from normal keyboard.

**Comment by sorgelig** [comment]
I have idea how to add it. But i have no jammaSD to test.

what mean these records?
```
{KEY_BACKSPACE, 1, 0},    // 1P up shifted
    {KEY_P,         1, 0},    // 1P down shifted
    {KEY_ENTER,     1, 0},    // 1P left shifted
    {KEY_TAB,       1, 0},    // 1P right shifted
    // {KEY_5,         1, 4}, // 1P 1 shifted (defined above)
    // {KEY_6,         1, 5}, // 1P 2 shifted (defined above)
    {KEY_ESC,       2, KEY_1} // 2P start shifted
```
are these keys are physically separate? Wat meas "1P shifted"?

**Comment by sorgelig** [comment]
oh, i've saw your comment in the code.

**Comment by vikbez** [comment]
These records are for knowing if the input comes from player 1 or 2; (the 3rd column is useless for P1, I have to improve the code if we go that route)

You can find the jammasd outputs here (page 2) https://www.webasd.com/public/doc/ASD275D/JammASDusb_Pinout.pdf

Ok you saw the comments. For now when shifting I did the code to behave like the input is the same key.

**Comment by sorgelig** [comment]
I've pushed the change to support JammaSD.
you need to add into MiSTer.ini:
```
jammasd_vid=0x04D8
jammasd_pid=0xF3AD
```
then MiSTer should see it as 2 joysticks which you have to map in Menu core initially.

**Comment by vikbez** [comment]
I tested and it works. Closing this ! Thanks

**Pull request closed without merging**
