### PR TITLE
Auto rotation and video info

### PR DESCRIPTION
**Pull request by wickerwaka**
Read the rotation flag when updating the video info. When the simulated display is rotated, when rotate the shadow masks and video filters also. Also calculate vscale using the width instead of the height so integer scaling is applied correctly.

Save the video info from the core and display it in the Information area (as long as there isn't a battery connected!)

Video Info in OSD

Split up code a little so retrieving the info, showing it in based on `video_info` and apply the video mode are separate functions.

Depends on https://github.com/MiSTer-devel/Template_MiSTer/pull/50 for the rotation flag.

### CODE REVIEW

**Comment by wickerwaka** [comment]
One thing I haven't tested but should: scandoubler fx scanlines. Those scanlines won't rotate, but the filters will, probably causing some undesirable results. Maybe the rotation flag should not be set if scandoubler scanlines are enabled?

**Comment by sorgelig** [comment]
rotated video should not rotate shadow mask just by original logic. Original CRT monitors used vertically still were normal monitors with horizontal mask.

**Comment by sorgelig** [comment]
Neither scanlines nor shadow mask should rotate. Vertical CRT display doesn't rotate hs/vs signals. Scanlines on vertical display should be vertical!

**Comment by wickerwaka** [comment]
That's what this change does, but it's confusing to talk about! The rotation flag is set when we are *simulating* a rotated display using the `screen_rotate` module, in that case you do want the filters and masks to rotate.

**Comment by sorgelig** [comment]
There was no intention to simulate rotated display because it gives dissonance looking on normal horizontal display with vertical scanlines.

**Comment by wickerwaka** [comment]
I don't see what problems it creates but it does solve two problems:
* Fixes `vscale_mode` for these cores, currently people have to use calculated `vscale_border` values in order to get integer scaling
* No need for separate vertical and horizontal video presets

**Comment by sorgelig** [comment]
agree for vscale_mode, but not vertical scanlines on horizontal display. Presets already can do it - so leave it there.

**Comment by wickerwaka** [comment]
Updated it so it no longer does the rotation.

**Pull request merged**
