### PR TITLE
Auto-bootstrap GCC, and force plink to cache the host key

### PR DESCRIPTION
**Pull request by c0d3h4x0r**
Just a suggestion to make things a bit easier.

### CODE REVIEW

**Comment by sorgelig** [comment]
this is wrong. there can be different compatible versions of gcc. It's not corrct to forcing to specific gcc version/build as it will mess developing environment.

**Comment by c0d3h4x0r** [comment]
Would this be okay as a default, only if `CC` is not already set?

**Comment by sorgelig** [comment]
i use this script as part of build process. It's not supposed to download anything. It's not for normal user, it's for developer. Therefore such auto downloads aren't acceptable here. I prefer it fail rather than auto-modification in system.

**Comment by c0d3h4x0r** [comment]
Yes, I know who this script is for and what it does.

Most developers like to save time and make things easier on themselves.  My goal here is to make building easier for the developer who is trying to build this repo for the first time, and for the developer who hasn't fetched and built it in a long time so their GCC toolchain is out-of-date and causing build errors.

Would you object to a new/separate script called something like `setup_build_toolchain.sh`?

**Comment by sorgelig** [comment]
ok

**Comment by c0d3h4x0r** [comment]
Done.

**Pull request merged**
