### PR TITLE
Saturn: fix the Seek command. SNES: increase the maximum bsram size to 256Kb.

### PR DESCRIPTION
**Pull request by srg320**

### CODE REVIEW

**Comment by kandowontu** [comment]
Thank you!!!

**Comment by kandowontu** [comment]
Just a heads up, this is having some issues while testing Super Mario Bros Maker.

**Comment by birdybro** [comment]
It might not be complete without changes to the snes core, this might be one part of the changes.

**Comment by kandowontu** [comment]
> It might not be complete without changes to the snes core, this might be one part of the changes.

Ahhh gotcha! Didn’t even think of that 🫠

**Pull request merged**
