### PR TITLE
Video Processing menu improvements

### PR DESCRIPTION
**Pull request by zakk4223**
Show filename instead of entire path.
On file picker lines, enable plus/minus to move through files in the same directory quickly.

### CODE REVIEW

**Comment by sorgelig** [comment]
I didn't get the meaning of +/-.. doesn't pgup/pgdown or left/right work for you?
patch seems too complicated, i can make it simpler if it's just to display names without paths.

**Comment by zakk4223** [comment]
maybe easier to describe via short video:

https://user-images.githubusercontent.com/22642/153356149-83f6eebf-1b7d-416f-8486-8549be41399c.mp4

**Comment by sorgelig** [comment]
i see

**Comment by sorgelig** [comment]
i've added this functionality.

**Pull request closed without merging**
